#!/bin/bash
#
if [[ "$1" == "-k" ]]; then 
  KWIN_OVERRIDE=true
else 
  KWIN_OVERRIDE=
  unset KWIN_OVERRIDE
fi
if [ -n "${KWIN_OVERRIDE}" ]; then
  k
  xfwm4 --replace & disown
  kwin_x11 --replace &
  kglobalaccel5 # for keyboard shortcuts like alttab
else
  xfwm4 --replace
fi
