#!/usr/bin/env bash
# This file is automatically generated


 
######## /home/mt/src/github/dots/filesystemarrayutil.sh function loaders begin here ########
declare -F "superblock_zero" > /dev/null 2>&1 || superblock_zero() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; superblock_zero "$@"
  return "$?"
}

declare -F "in_array" > /dev/null 2>&1 || in_array() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; in_array "$@"
  return "$?"
}

declare -F "finddir_array" > /dev/null 2>&1 || finddir_array() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; finddir_array "$@"
  return "$?"
}

declare -F "find_array" > /dev/null 2>&1 || find_array() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; find_array "$@"
  return "$?"
}

declare -F "assemble_bash_safe_path" > /dev/null 2>&1 || assemble_bash_safe_path() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; assemble_bash_safe_path "$@"
  return "$?"
}

declare -F "components_to_path" > /dev/null 2>&1 || components_to_path() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; components_to_path "$@"
  return "$?"
}

declare -F "string_to_safe_filename" > /dev/null 2>&1 || string_to_safe_filename() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; string_to_safe_filename "$@"
  return "$?"
}

declare -F "stringify" > /dev/null 2>&1 || stringify() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; stringify "$@"
  return "$?"
}

declare -F "quoted_stringify" > /dev/null 2>&1 || quoted_stringify() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; quoted_stringify "$@"
  return "$?"
}

declare -F "most_recent_in_dir" > /dev/null 2>&1 || most_recent_in_dir() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; most_recent_in_dir "$@"
  return "$?"
}

declare -F "most_recent_char_replaced_separated" > /dev/null 2>&1 || most_recent_char_replaced_separated() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; most_recent_char_replaced_separated "$@"
  return "$?"
}

declare -F "array_to_set" > /dev/null 2>&1 || array_to_set() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; array_to_set "$@"
  return "$?"
}

declare -F "array_intersection" > /dev/null 2>&1 || array_intersection() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; array_intersection "$@"
  return "$?"
}

declare -F "strip_paths" > /dev/null 2>&1 || strip_paths() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; strip_paths "$@"
  return "$?"
}

declare -F "same_plugin_same_type_diff_location" > /dev/null 2>&1 || same_plugin_same_type_diff_location() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; same_plugin_same_type_diff_location "$@"
  return "$?"
}

declare -F "fix_filenames" > /dev/null 2>&1 || fix_filenames() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; fix_filenames "$@"
  return "$?"
}

declare -F "can_i_read" > /dev/null 2>&1 || can_i_read() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; can_i_read "$@"
  return "$?"
}

declare -F "can_i_write" > /dev/null 2>&1 || can_i_write() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; can_i_write "$@"
  return "$?"
}

declare -F "can_i_do" > /dev/null 2>&1 || can_i_do() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do; source "/home/mt/src/github/dots/filesystemarrayutil.sh"; can_i_do "$@"
  return "$?"
}

_unset_filesystemarrayutilsh_fs() {
  unset -f superblock_zero in_array finddir_array find_array assemble_bash_safe_path components_to_path string_to_safe_filename stringify quoted_stringify most_recent_in_dir most_recent_char_replaced_separated array_to_set array_intersection strip_paths same_plugin_same_type_diff_location fix_filenames can_i_read can_i_write can_i_do;
  return "$?"
}

######## /home/mt/src/github/dots/filesystemarrayutil.sh function loaders end here ##########
 
######## /home/mt/src/github/dots/pathlib.sh function loaders begin here ########
declare -F "path_append" > /dev/null 2>&1 || path_append() {
  unset -f path_append path_prepend _setup_path _pathlib_fs; source "/home/mt/src/github/dots/pathlib.sh"; path_append "$@"
  return "$?"
}

declare -F "path_prepend" > /dev/null 2>&1 || path_prepend() {
  unset -f path_append path_prepend _setup_path _pathlib_fs; source "/home/mt/src/github/dots/pathlib.sh"; path_prepend "$@"
  return "$?"
}

declare -F "_setup_path" > /dev/null 2>&1 || _setup_path() {
  unset -f path_append path_prepend _setup_path _pathlib_fs; source "/home/mt/src/github/dots/pathlib.sh"; _setup_path "$@"
  return "$?"
}

declare -F "_pathlib_fs" > /dev/null 2>&1 || _pathlib_fs() {
  unset -f path_append path_prepend _setup_path _pathlib_fs; source "/home/mt/src/github/dots/pathlib.sh"; _pathlib_fs "$@"
  return "$?"
}

_unset_pathlibsh_fs() {
  unset -f path_append path_prepend _setup_path _pathlib_fs;
  return "$?"
}

######## /home/mt/src/github/dots/pathlib.sh function loaders end here ##########
 
######## /home/mt/src/github/dots/user_prompts.sh function loaders begin here ########
declare -F "get_keypress" > /dev/null 2>&1 || get_keypress() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; get_keypress "$@"
  return "$?"
}

declare -F "get_yes_keypress" > /dev/null 2>&1 || get_yes_keypress() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; get_yes_keypress "$@"
  return "$?"
}

declare -F "confirm_yes" > /dev/null 2>&1 || confirm_yes() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; confirm_yes "$@"
  return "$?"
}

declare -F "confirm_yes_default_no" > /dev/null 2>&1 || confirm_yes_default_no() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; confirm_yes_default_no "$@"
  return "$?"
}

declare -F "get_timed_keypress" > /dev/null 2>&1 || get_timed_keypress() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; get_timed_keypress "$@"
  return "$?"
}

declare -F "get_timed_yes" > /dev/null 2>&1 || get_timed_yes() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; get_timed_yes "$@"
  return "$?"
}

declare -F "timed_confirm_yes" > /dev/null 2>&1 || timed_confirm_yes() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; timed_confirm_yes "$@"
  return "$?"
}

declare -F "timed_confirm_yes_default_no" > /dev/null 2>&1 || timed_confirm_yes_default_no() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; timed_confirm_yes_default_no "$@"
  return "$?"
}

declare -F "choices" > /dev/null 2>&1 || choices() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices; source "/home/mt/src/github/dots/user_prompts.sh"; choices "$@"
  return "$?"
}

_unset_userpromptssh_fs() {
  unset -f get_keypress get_yes_keypress confirm_yes confirm_yes_default_no get_timed_keypress get_timed_yes timed_confirm_yes timed_confirm_yes_default_no choices;
  return "$?"
}

######## /home/mt/src/github/dots/user_prompts.sh function loaders end here ##########
